Initial version
truenas/api_client pull request #1
Opened 2024-06-03 14:57 UTC by themylogin

2024-06-03 14:57 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-129371

2024-06-03 15:55 UTC, william-gr commented
Probably need a .gitignore for the pycache files ;)

2024-06-03 16:34 UTC, yocalebo requested changes

2024-06-03 16:34 UTC, yocalebo commented on debian/control
> +               python3-fastentrypoints,
We don't need fastentrypoints.

2024-06-03 16:34 UTC, yocalebo commented on debian/control
> +               python3-libzfs,
I don't like making our websocket client dependent on this package. I'd rather just hard-code these ZFS errors inside this module itself and deal with maintaining it.

2024-06-05 11:16 UTC, yocalebo approved these changes

2024-06-05 11:21 UTC, merged

2024-06-05 11:21 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.